# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo1
    pod 'AFNetworking', '~> 3.2.1'
    pod 'CocoaAsyncSocket', '~> 7.6.3'


  target 'Demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
